### ISSUE TITLE
样本无法生成

### ISSUE THREAD

**Issue by obelia01** [Pizz33/JoJoLoader#12]
<img width="1305" alt="image" src="https://github.com/user-attachments/assets/951a7011-4ef7-463e-9ca3-9d44861fcf5b">
哥哥、这个样本生成不了，提示
encrypt.bin、"uuidkey.txt"文件不存在啊

**Comment by Pizz33** [comment]
> <img width="1305" alt="image" src="https://github.com/user-attachments/assets/951a7011-4ef7-463e-9ca3-9d44861fcf5b">
> 
> 哥哥、这个样本生成不了，提示
> 
> encrypt.bin、"uuidkey.txt"文件不存在啊

大概率是你的python命名为python3 改一下bat中的python为python3即可

**Comment by mango-wb** [comment]
佬，我在物理机编译了项目，运行之后可以上线cs，但是在虚拟机点开无法上线，也没有被wd拦截，感觉像是生成的exe缺啥东西，你遇到这个问题了吗
