### ISSUE TITLE
依赖都装好后直接运行脚本出现以下的报错

### ISSUE THREAD

**Issue by ketchup1995** [Pizz33/JoJoLoader#5]
Generated UUID key: 0eac50b7-8bc6-44e4-be77-5d50d20dc5a3
UUID key saved to src/uuidkey.txt
Encrypted data saved to src/encrypt.bin
   Compiling libc v0.2.155
   Compiling crossbeam-utils v0.8.20
   Compiling winapi v0.3.9
   Compiling vswhom-sys v0.1.2
error: linker `link.exe` not found
  |
  = note: program not found

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that Visual Studio 2017 or later, or Build Tools for Visual Studio were installed with the Visual C++ option.

note: VS Code is a different product, and is not sufficient.

error: could not compile `vswhom-sys` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `crossbeam-utils` (build script) due to 1 previous error
error: could not compile `libc` (build script) due to 1 previous error
error: could not compile `winapi` (build script) due to 1 previous error
系统找不到指定的文件。
Copied and renamed to: "output\sZYHXX.exe"
Traceback (most recent call last):
  File "C:\Users\aakou\Desktop\JoJoLoader-main\JoJoLoader-main\output\sigthief.py", line 247, in <module>
    writeCert(cert, options.targetfile, options.outputfile)
  File "C:\Users\aakou\Desktop\JoJoLoader-main\JoJoLoader-main\output\sigthief.py", line 120, in writeCert
    flItms = gather_file_info_win(exe)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aakou\Desktop\JoJoLoader-main\JoJoLoader-main\output\sigthief.py", line 18, in gather_file_info_win
    binary = open(binary, 'rb')
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'output\\sZYHXX.exe'

**Comment by Pizz33** [comment]
> Generated UUID key: 0eac50b7-8bc6-44e4-be77-5d50d20dc5a3 UUID key saved to src/uuidkey.txt Encrypted data saved to src/encrypt.bin Compiling libc v0.2.155 Compiling crossbeam-utils v0.8.20 Compiling winapi v0.3.9 Compiling vswhom-sys v0.1.2 error: linker `link.exe` not found | = note: program not found
> 
> note: the msvc targets depend on the msvc linker but `link.exe` was not found
> 
> note: please ensure that Visual Studio 2017 or later, or Build Tools for Visual Studio were installed with the Visual C++ option.
> 
> note: VS Code is a different product, and is not sufficient.
> 
> error: could not compile `vswhom-sys` (build script) due to 1 previous error warning: build failed, waiting for other jobs to finish... error: could not compile `crossbeam-utils` (build script) due to 1 previous error error: could not compile `libc` (build script) due to 1 previous error error: could not compile `winapi` (build script) due to 1 previous error 系统找不到指定的文件。 Copied and renamed to: "output\sZYHXX.exe" Traceback (most recent call last): File "C:\Users\aakou\Desktop\JoJoLoader-main\JoJoLoader-main\output\sigthief.py", line 247, in writeCert(cert, options.targetfile, options.outputfile) File "C:\Users\aakou\Desktop\JoJoLoader-main\JoJoLoader-main\output\sigthief.py", line 120, in writeCert flItms = gather_file_info_win(exe) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\aakou\Desktop\JoJoLoader-main\JoJoLoader-main\output\sigthief.py", line 18, in gather_file_info_win binary = open(binary, 'rb') ^^^^^^^^^^^^^^^^^^ FileNotFoundError: [Errno 2] No such file or directory: 'output\sZYHXX.exe'

报错都在上面写了 你按照我文档的方法安装然后加环境变量就没问题
note: the msvc targets depend on the msvc linker but link.exe was not found
note: please ensure that Visual Studio 2017 or later, or Build Tools for Visual Studio were installed with the Visual C++ option.
