### ISSUE TITLE
360云木马查杀好像过不了了

### ISSUE THREAD

**Issue by junanc** [Pizz33/JoJoLoader#6]
测试了好多次，每次测试都换一个ico,   然后也测试了更换数字签名。好像现在被特征了。都不行已经过不了了

<img width="1103" alt="image" src="https://github.com/Pizz33/JoJoLoader/assets/44342736/b92f9e1f-6c72-458e-a273-86e7e8451102">
<img width="652" alt="image" src="https://github.com/Pizz33/JoJoLoader/assets/44342736/0f95c958-b3b5-4e52-90d4-a7d2b22b2c62">

**Comment by Pizz33** [comment]
> 测试了好多次，每次测试都换一个ico, 然后也测试了更换数字签名。好像现在被特征了。都不行已经过不了了
> 
> <img alt="image" width="1103" src="https://private-user-images.githubusercontent.com/44342736/346503015-b92f9e1f-6c72-458e-a273-86e7e8451102.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTk3NTUsIm5iZiI6MTcyMDUxOTQ1NSwicGF0aCI6Ii80NDM0MjczNi8zNDY1MDMwMTUtYjkyZjllMWYtNmM3Mi00NThlLWEyNzMtODZlN2U4NDUxMTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDEwMDQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNmY0NjQwZGM0NjE1ODE1OGQ4YjQyYzY5NTY0NDhiOTNiYWIzM2RhYzE1OWM3Y2EzNTVkNjViYWYxZDAwN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G-AjBpiaC-RSgMGHAQXt1NILTYCJxhuVOPQVVkJEUcY"> <img alt="image" width="652" src="https://private-user-images.githubusercontent.com/44342736/346503152-0f95c958-b3b5-4e52-90d4-a7d2b22b2c62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTk3NTUsIm5iZiI6MTcyMDUxOTQ1NSwicGF0aCI6Ii80NDM0MjczNi8zNDY1MDMxNTItMGY5NWM5NTgtYjNiNS00ZTUyLTkwZDQtYTdkMmIyMmIyYzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDEwMDQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkODA4NDk0ZmYwYTlhZDA5N2Y0MjlhYzM1MDBlY2EwNTFmMzJjMzFhMWFkYTE2OWRlZjJlNTJlNWQ1MzFiY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MDJRfw0Ww5ZkfkcxwyAMyq4ObNDq9pMpQZJJlTjpv64">

自行改改代码= =

**Comment by junanc** [comment]
大概需要改什么地方啊，能不能简单说一下， 我去研究研究

**Comment by Pizz33** [comment]
> 大概需要改什么地方啊，能不能简单说一下， 我去研究研究

换一种加密方式，或者选用不同的参数进行编译
[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
debug = false
panic = "abort"
